on:
  push:
    branches: 
      - '*'
      - '!main'
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - synchronize


jobs:
  plan:
    if: github.repository != 'Tanchwa/infrastructure-deployment-template'
    name: 'Terraform Plan'
    uses: Tanchwa/workflows-terraform-deployment/.github/workflows/terraform_plan.yaml@v0.2.0
    secrets: 
      CHANGE_ME: CHANGE_ME
      CHANGE_ME2: CHANGE_ME
      CHANGE_ME_ALSO: CHANGE_ME
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      terraform_version: "1.12"
      working_directory: "."

  apply:
    if: (github.event.pull_request.merged && github.base_ref == 'main') && github.repository != 'Tanchwa/infrastructure-deployment-template'
    needs: plan
    name: 'Terraform Apply'
    uses: Tanchwa/workflows-terraform-deployment/.github/workflows/terraform_apply.yaml@v0.2.0
    secrets: 
      CHANGE_ME: CHANGE_ME
      CHANGE_ME2: CHANGE_ME
      CHANGE_ME_ALSO: CHANGE_ME
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      terraform_version: "1.12"
      working_directory: "."
      terraform_plan_file: ${{ needs.plan.outputs.plan_file }}
